server :
    port : 80


spring :
    mvc :
        view :
            prefix : /views/ 
            suffix : .jsp   
    datasource :
        driver-class-name : com.mysql.cj.jdbc.Driver
        url : jdbc:mysql://192.168.0.84:32933/kdt_12_3d_gw?characterEncoding=utf-8
        username : kdt_gw
        password : 1234
#내 : 192.168.0.84
#외 : citek707.iptime.org
mybatis :
    configuration :
        map-underscore-to-camel-case : true
